language: generic
sudo: false
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
before_install:
  - sudo evm install $EVM_EMACS --use --skip
script:
  - echo "TEST"
  - emacs --version
  - make EMACS=${EMACS} check
